(function () {
  const bundled = location.protocol === "file:" || location.pathname.includes("/KwantuHub/");
  const path = (name) => bundled ? `assets/${name}` : `/manus-storage/${name}`;
  window.KwantuCatalog = [
    { id: "adire-silk", kind: "product", category: "Fabrics & Textiles", title: "Hand-Dyed Adire Occasion Fabric — 5 Yards", short: "Indigo-resist textile selected for celebrations, tailoring, and meaningful gifts.", description: "A rich hand-dyed adire textile selected by Aunty Eki’s Ankara for occasion dressing and heirloom tailoring. The pattern carries a vivid indigo story with a versatile five-yard cut.", price: "$85", vendor: "Aunty Eki’s Ankara", location: "Houston, TX · USA", image: path("kwantu-ceremony-tailor_6da99e5d.jpg"), size: "tall" },
    { id: "ankara-wrap", kind: "product", category: "Fabrics & Textiles", title: "Ankara Celebration Wrap", short: "A bright everyday wrap from a Houston textile archive.", description: "A joyful Ankara wrap for gatherings, gifting, and everyday expression, selected from Aunty Eki’s rotating fabric archive.", price: "$74", vendor: "Aunty Eki’s Ankara", location: "Houston, TX · USA", image: path("kwantu-hero-fashion-maker_20399257.jpg"), size: "short" },
    { id: "yoruba-immersion", kind: "service", category: "Language Learning", title: "1-on-1 Yorùbá Language Immersion for Kids", short: "Gentle, family-centred language sessions built around story and play.", description: "Studio Yorùbá offers one-to-one sessions that give children a warm place to hear, practise, and carry language into daily family life.", price: "$35 / hr", vendor: "Studio Yorùbá", location: "Chicago, IL · USA", image: path("kwantu-tutor-family_96516297.jpg"), size: "short" },
    { id: "yoruba-circle", kind: "service", category: "Language Learning", title: "Yorùbá Conversation Circle", short: "Small-group practice for adults returning to language.", description: "A conversational setting for adults building confidence with Yorùbá sounds, everyday phrases, and cultural context.", price: "$20 / session", vendor: "Studio Yorùbá", location: "Chicago, IL · USA", image: path("kwantu-tutor-family_96516297.jpg"), size: "" },
    { id: "kenyan-feast", kind: "service", category: "Foods & Catering", title: "East African Celebration Catering", short: "A generous, story-led menu for gatherings large and small.", description: "Spice Route Kenya prepares East African menus for home celebrations, cultural events, and office gatherings, with every table shaped around hospitality.", price: "From $180", vendor: "Spice Route Kenya", location: "Minneapolis, MN · USA", image: path("kwantu-hero-caterer_500a9501.jpg"), size: "tall" },
    { id: "suya-spice", kind: "product", category: "Foods & Catering", title: "Suya Spice & Smoky Pepper Blend", short: "A small-batch pantry blend for expressive weeknight cooking.", description: "A fragrant spice mix by Spice Route Kenya, blended for roasted vegetables, grilled proteins, and deep, smoky comfort.", price: "$18", vendor: "Spice Route Kenya", location: "Minneapolis, MN · USA", image: path("kwantu-hero-caterer_500a9501.jpg"), size: "short" },
    { id: "braid-consult", kind: "service", category: "Beauty & Natural Hair", title: "Knotless Braids & Natural Hair Consultation", short: "Protective styling with a considered care plan for your hair.", description: "Mama Africa Braids combines tailored consultation with protective styling, so every appointment begins with healthy hair and your desired look.", price: "$160", vendor: "Mama Africa Braids", location: "Toronto, ON · Canada", image: path("kwantu-braider_2d92759f.jpg"), size: "tall" },
    { id: "natural-hair-ritual", kind: "service", category: "Beauty & Natural Hair", title: "Natural Hair Ritual & Scalp Care", short: "A restorative appointment for textured hair and scalp comfort.", description: "A focused natural-hair care session from Mama Africa Braids, centred on scalp wellbeing, moisture, and sustainable maintenance.", price: "$70", vendor: "Mama Africa Braids", location: "Toronto, ON · Canada", image: path("kwantu-braider_2d92759f.jpg"), size: "" },
  ];
})();
